"use client";

import Link from "next/link";
import { notFound, useParams } from "next/navigation";
import { useMemo } from "react";
import { useMockApp } from "@/components/providers/mock-app-provider";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { LoadingBlocks } from "@/components/ui/loading-blocks";
import { PageHeader } from "@/components/ui/page-header";
import { Panel } from "@/components/ui/panel";
import { ProgressBar } from "@/components/ui/progress-bar";
import { StatusPill } from "@/components/ui/status-pill";
import { usePageReady } from "@/lib/use-page-ready";

export default function ProjectPage() {
  const params = useParams<{ id: string }>();
  const ready = usePageReady();
  const { state, renderShortDraft, renderAllDraftsForProject, approveShortDraft, rejectShortDraft, queueShortForPublishing, updateProject } = useMockApp();

  const project = state.projects.find((item) => item.id === params.id);
  const sourceVideos = useMemo(() => state.sourceVideos.filter((video) => project?.sourceVideoIds.includes(video.id)), [project?.sourceVideoIds, state.sourceVideos]);
  const drafts = useMemo(() => state.editedShorts.filter((draft) => draft.projectId === params.id), [params.id, state.editedShorts]);
  const primaryDraft = drafts.find((draft) => draft.id === project?.primaryShortId) ?? drafts.find((draft) => draft.primary) ?? drafts[0];
  const alternateDrafts = drafts.filter((draft) => draft.id !== primaryDraft?.id);

  if (!project && ready) {
    notFound();
  }

  if (!ready || !project) {
    return <LoadingBlocks rows={4} />;
  }

  const textPackage = project.textPackage;

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Project"
        title={project.title}
        description="Review what AI generated, then open the short draft to approve and download."
        actions={
          <>
            {primaryDraft ? (
              <Link href={`/shorts/${primaryDraft.id}`} className="inline-flex items-center rounded-full bg-ink px-4 py-2 text-sm font-semibold text-white">
                Open short draft →
              </Link>
            ) : null}
            <Button onClick={() => void renderAllDraftsForProject(project.id)}>Render all drafts</Button>
            <Link href="/library" className="inline-flex items-center rounded-full border border-ink/15 px-4 py-2 text-sm font-semibold text-ink">
              Back to library
            </Link>
          </>
        }
      />

      {/* Fallback warning — now shows the actual error cause */}
      {project.status === "fallback" || project.warning ? (
        <div className="rounded-2xl border border-amber-300 bg-amber-50 p-4">
          <div className="flex items-start gap-3">
            <span className="mt-0.5 text-xl">⚠️</span>
            <div>
              <p className="font-semibold text-amber-900">Parts of this project used fallback generation</p>
              <p className="mt-1 text-sm text-amber-800">
                {project.warning ?? "One or more AI providers were unavailable. Check the pipeline steps below for the specific error."}
              </p>
            </div>
          </div>
        </div>
      ) : null}

      <section className="grid gap-4 xl:grid-cols-[0.82fr_1.18fr]">
        {/* LEFT: Pipeline steps + text package + source videos */}
        <div className="space-y-4">

          {/* Pipeline steps */}
          <Panel className="space-y-4">
            <div>
              <h2 className="text-xl font-semibold text-ink">Generation pipeline</h2>
              <p className="text-sm text-slate-600">Each step runs in sequence. Fallback means AI was unavailable and a local alternative was used.</p>
            </div>
            <div className="space-y-3">
              {project.progressSteps.map((step) => {
                const isFallback = step.status === "fallback";
                const isComplete = step.status === "complete";
                const defaultMessage =
                  step.id === "step-transcribe" && isComplete ? "Audio transcribed using Groq Whisper." :
                  step.id === "step-transcribe" && isFallback ? "Groq unavailable — simulated transcript used. Subtitles may not match audio." :
                  step.id === "step-vision" && isComplete ? "Video analyzed by Gemini — moments chosen from visual and audio cues." :
                  step.id === "step-vision" && isFallback ? "Gemini unavailable — moments chosen by keyword matching instead." :
                  step.id === "step-text" && isFallback ? "OpenRouter unavailable — fallback text templates used." :
                  step.id === "step-text" && isComplete ? "Concept angle and copy options generated by OpenRouter." :
                  isComplete ? "Complete." : null;

                return (
                  <div key={step.id} className={`rounded-2xl border p-4 ${isFallback ? "border-amber-300 bg-amber-50/50" : "border-slate-200"}`}>
                    <div className="flex items-center justify-between gap-3">
                      <p className="font-semibold text-ink">{step.label}</p>
                      <StatusPill label={step.status} />
                    </div>
                    {/* Show actual error message if present, otherwise show default */}
                    {(step.message ?? defaultMessage) ? (
                      <p className={`mt-1.5 text-sm ${isFallback ? "text-amber-800" : "text-slate-600"}`}>
                        {step.message ?? defaultMessage}
                      </p>
                    ) : null}
                  </div>
                );
              })}
            </div>
          </Panel>

          {/* Source videos */}
          <Panel className="space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="text-xl font-semibold text-ink">Source videos</h2>
              <StatusPill label={`${sourceVideos.length} video${sourceVideos.length === 1 ? "" : "s"}`} />
            </div>
            {sourceVideos.map((video) => (
              <div key={video.id} className="rounded-2xl bg-slate-50 p-4">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="font-semibold text-ink">{video.title}</p>
                    <p className="text-sm text-slate-600">{video.description}</p>
                    <p className="mt-2 text-xs uppercase tracking-[0.2em] text-slate-500">{video.duration}</p>
                  </div>
                  <div className="flex flex-col gap-2">
                    <StatusPill label={video.transcriptStatus} />
                    <StatusPill label={video.analysisStatus} />
                    {video.transcriptSource && video.transcriptSource !== "hosted" ? (
                      <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800">⚠️ simulated</span>
                    ) : null}
                  </div>
                </div>
                {video.transcriptPreview ? <p className="mt-3 text-sm italic text-slate-700">"{video.transcriptPreview}"</p> : null}
              </div>
            ))}
          </Panel>
        </div>

        {/* RIGHT: Text package + short drafts */}
        <div className="space-y-4">

          {/* Full text package */}
          <Panel className="space-y-5">
            <div>
              <h2 className="text-xl font-semibold text-ink">Text package</h2>
              <p className="text-sm text-slate-600">Everything OpenRouter generated for this idea. These feed the short draft's hook, caption, hashtags, and overlays.</p>
            </div>

            <div className="rounded-2xl bg-slate-50 p-4">
              <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Concept angle</p>
              <p className="mt-2 text-sm text-slate-800">{textPackage.conceptAngle}</p>
            </div>

            <div className="rounded-2xl bg-slate-50 p-4">
              <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Hook options</p>
              <div className="mt-2 flex flex-col gap-2">
                {textPackage.hookOptions.map((hook, i) => (
                  <p key={i} className="text-sm text-slate-800">"{hook}"</p>
                ))}
              </div>
            </div>

            <div className="rounded-2xl bg-slate-50 p-4">
              <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Caption options</p>
              <div className="mt-2 flex flex-col gap-2">
                {textPackage.captionOptions.map((caption, i) => (
                  <p key={i} className="text-sm text-slate-800">"{caption}"</p>
                ))}
              </div>
            </div>

            <div className="rounded-2xl bg-slate-50 p-4">
              <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Clickbait title options</p>
              <div className="mt-2 flex flex-col gap-2">
                {textPackage.clickbaitTitleOptions.map((title, i) => (
                  <p key={i} className="text-sm font-medium text-slate-800">{title}</p>
                ))}
              </div>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              <div className="rounded-2xl bg-slate-50 p-4">
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Hashtags</p>
                <div className="mt-2 flex flex-wrap gap-1.5">
                  {textPackage.hashtagOptions.map((tag) => (
                    <span key={tag} className="rounded-full bg-slate-200 px-2.5 py-0.5 text-xs font-semibold text-slate-700">{tag}</span>
                  ))}
                </div>
              </div>

              <div className="rounded-2xl bg-slate-50 p-4">
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">CTA options</p>
                <div className="mt-2 flex flex-col gap-1.5">
                  {textPackage.ctaOptions.map((cta, i) => (
                    <p key={i} className="text-sm text-slate-800">"{cta}"</p>
                  ))}
                </div>
              </div>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              <div className="rounded-2xl bg-slate-50 p-4">
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Funny caption ideas</p>
                <div className="mt-2 flex flex-col gap-1.5">
                  {textPackage.funnyCaptionIdeas.map((idea, i) => (
                    <p key={i} className="text-sm text-slate-800">"{idea}"</p>
                  ))}
                </div>
              </div>

              <div className="rounded-2xl bg-slate-50 p-4">
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">First comment</p>
                <div className="mt-2 flex flex-col gap-1.5">
                  {textPackage.firstCommentOptions.map((comment, i) => (
                    <p key={i} className="text-sm text-slate-800">"{comment}"</p>
                  ))}
                </div>
              </div>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              <div className="rounded-2xl bg-slate-50 p-4">
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Subtitle tone</p>
                <p className="mt-2 text-sm text-slate-800">{textPackage.subtitleToneSuggestion}</p>
              </div>
              <div className="rounded-2xl bg-slate-50 p-4">
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Editing vibe</p>
                <p className="mt-2 text-sm text-slate-800">{textPackage.editingVibeSuggestion}</p>
              </div>
            </div>
          </Panel>

          {/* Primary short draft */}
          <Panel className="space-y-4">
            <div className="flex items-center justify-between gap-3">
              <div>
                <h2 className="text-xl font-semibold text-ink">Primary short draft</h2>
                <p className="text-sm text-slate-600">The strongest generated cut. Render a preview, then open the draft to approve and download.</p>
              </div>
              {primaryDraft ? <StatusPill label={primaryDraft.renderStatus ?? "not_started"} /> : null}
            </div>

            {!primaryDraft ? (
              <EmptyState title="No draft created yet" detail="Generate the project again after adding source videos to create a stitched short draft." />
            ) : (
              <div className="space-y-4">
                <div className="rounded-3xl border border-slate-200 p-5">
                  <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
                    <div className="space-y-2">
                      <div className="flex flex-wrap gap-2">
                        <p className="font-semibold text-ink">{primaryDraft.title}</p>
                        {primaryDraft.primary ? <StatusPill label="primary" /> : null}
                        {primaryDraft.draftStatus ? <StatusPill label={primaryDraft.draftStatus} /> : null}
                      </div>
                      <p className="text-sm text-slate-700">{primaryDraft.hook}</p>
                      <p className="text-sm text-slate-600">{primaryDraft.caption}</p>
                      <div className="flex flex-wrap gap-2">
                        {primaryDraft.overlayText.map((item) => (
                          <span key={item} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700">{item}</span>
                        ))}
                      </div>
                    </div>
                    <div className="shrink-0 space-y-1 text-sm text-slate-600">
                      <p>{primaryDraft.shortPlanSegments?.length ?? 0} segments</p>
                      <p>{primaryDraft.subtitleCues?.length ?? 0} subtitles</p>
                      <p>{primaryDraft.overlayCaptions?.length ?? 0} overlays</p>
                    </div>
                  </div>

                  {primaryDraft.previewUrl ? (
                    <div className="mt-4 rounded-2xl bg-slate-50 p-4">
                      <video
                        src={primaryDraft.previewUrl}
                        controls
                        className="aspect-[9/16] w-full rounded-2xl bg-black object-contain"
                      />
                    </div>
                  ) : primaryDraft.renderStatus === "rendering" ? (
                    <div className="mt-4 rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 p-8 text-center">
                      <div className="mx-auto max-w-sm space-y-4">
                        <ProgressBar
                          progress={primaryDraft.renderProgress ?? 0}
                          message={primaryDraft.renderMessage ?? "Rendering draft..."}
                        />
                      </div>
                    </div>
                  ) : primaryDraft.renderError ? (
                    <div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4">
                      <p className="text-sm font-semibold text-red-800">Render failed</p>
                      <pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap break-all text-xs text-red-700">
                        {primaryDraft.renderError}
                      </pre>
                    </div>
                  ) : (
                    <div className="mt-4 rounded-2xl bg-slate-100 p-4 text-center text-sm text-slate-600">
                      No preview yet. Click "Generate preview" to render the stitched short.
                    </div>
                  )}

                  {/* Primary CTA: Open draft detail */}
                  <div className="mt-4 flex flex-wrap gap-3">
                    <Link href={`/shorts/${primaryDraft.id}`} className="inline-flex items-center rounded-full bg-ink px-4 py-2 text-sm font-semibold text-white">
                      Open draft detail →
                    </Link>
                    <Button onClick={() => void renderShortDraft(primaryDraft.id)}>
                      {primaryDraft.renderStatus === "ready" ? "Regenerate preview" : "Generate preview"}
                    </Button>
                    <Button variant="secondary" onClick={() => void approveShortDraft(primaryDraft.id)}>
                      Approve
                    </Button>
                    <Button variant="ghost" onClick={() => void queueShortForPublishing(primaryDraft.id)}>
                      Send to publishing
                    </Button>
                    <Button variant="ghost" onClick={() => void rejectShortDraft(primaryDraft.id)}>
                      Reject
                    </Button>
                  </div>
                </div>

                {/* Detected moments */}
                <div className="rounded-3xl border border-slate-200 p-5">
                  <div className="flex items-center justify-between">
                    <p className="text-sm font-semibold uppercase tracking-[0.24em] text-slate-500">Detected moments</p>
                    <StatusPill label={`${project.detectedMoments.length} moments`} />
                  </div>
                  {project.detectedMoments.length === 0 ? (
                    <p className="mt-3 text-sm text-slate-500">No moments detected.</p>
                  ) : (
                    <div className="mt-4 space-y-3">
                      {project.detectedMoments.map((moment) => (
                        <div key={moment.id} className="rounded-2xl bg-slate-50 p-4">
                          <div className="flex items-start justify-between gap-3">
                            <div>
                              <p className="font-semibold text-ink">{moment.label}</p>
                              <p className="text-sm text-slate-600">{moment.reason}</p>
                              {moment.transcriptExcerpt ? <p className="mt-2 text-sm italic text-slate-700">"{moment.transcriptExcerpt}"</p> : null}
                            </div>
                            <div className="flex shrink-0 flex-col gap-2">
                              <StatusPill label={`${moment.score} score`} />
                              <StatusPill label={moment.energy} />
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            )}
          </Panel>

          {/* Alternate drafts */}
          {alternateDrafts.length > 0 ? (
            <Panel className="space-y-4">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <h2 className="text-xl font-semibold text-ink">Alternate drafts</h2>
                  <p className="text-sm text-slate-600">Different cuts of the same footage. Swap one in as primary or review it directly.</p>
                </div>
                <StatusPill label={`${alternateDrafts.length} alternates`} />
              </div>
              <div className="space-y-3">
                {alternateDrafts.map((draft) => (
                  <div key={draft.id} className="rounded-2xl border border-slate-200 p-4">
                    <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
                      <div className="space-y-2">
                        <div className="flex flex-wrap items-center gap-2">
                          <p className="font-semibold text-ink">{draft.title}</p>
                          {draft.draftStatus ? <StatusPill label={draft.draftStatus} /> : null}
                        </div>
                        <p className="text-sm text-slate-700">{draft.hook}</p>
                      </div>
                      <div className="flex shrink-0 flex-wrap gap-2">
                        <Link href={`/shorts/${draft.id}`} className="inline-flex items-center rounded-full bg-ink px-4 py-2 text-sm font-semibold text-white">
                          Open →
                        </Link>
                        <Button variant="secondary" onClick={() => void renderShortDraft(draft.id)}>Render</Button>
                        <Button variant="ghost" onClick={() => void updateProject(project.id, { primaryShortId: draft.id })}>Make primary</Button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </Panel>
          ) : null}
        </div>
      </section>
    </div>
  );
}
